### ISSUE TITLE
Peer to peer code review 2/24/2023

### ISSUE THREAD

**Issue by Matthieu96Code** [MuhammadUsmanAslam/To-Do-List#4]
**To-Do List**

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on

- [ ]  kindly set a Webpack mode for your project, we suggest the development mode

- [ ] kindly create modules as you want to reduce the length of the main file of js

- [ ] Please remove a third party of unused packages
